board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    # path('<int:board_id>/create_reply', views.create_reply, name='create_reply'),
]

mysite/urls.py
## 최상위 URLconf 관리
## 콘트롤러 등록?
## 작성한 url을 연결

from django.contrib import admin
from django.urls import include, path

## include() > 다른 URLconf를 참조할 수 있게 해줌
## http://127.0.0.1:8000/polls와 연결
urlpatterns = [
    path('polls/', include('polls.urls')), 
    path('board/', include('board.urls')),
    path('admin/', admin.site.urls), 
]

polls/urls.py
from django.urls import path

from . import views
## 컨트롤러 소스? 서비스?
# http://127.0.0.1:8000/polls로 요청이 오면 views 내부에 index와 연결
urlpatterns = [
    path('', views.index, name='index'),
]

board/models.py
from django.db import models

class Board(models.Model):
    """
        addr: 사는곳
        sex: 성별
        author: 좋아하는 작가(다중 선택가능)
        create_date: 설문 조사일
    """
    addr = models.CharField(max_length=100)
    sex = models.CharField(max_length=3)
    age = models.CharField(max_length=3)
    author = models.CharField(max_length=3)
    hp = models.CharField(max_length=20)
    ##like_count = models.PositiveIntegerField(default=0) # 양수입력 필드
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.hp

class author(models.Model):
    """
        작가 코드 테이블
    """
    #reply = models.ForeignKey(Board, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.name

# class Reply(models.Model):
#     """
#         reply: Reply -> Board 연결관계
#         comment: 댓글내용
#         rep_date: 작성일
#     """
#     reply = models.ForeignKey(Board, on_delete=models.CASCADE)
#     comment = models.CharField(max_length=200)
#     rep_date = models.DateTimeField()

#     def __str__(self):
#         return self.comment

polls/models.py
from django.db import models

# Create your models here.

board/views.py
# from django.shortcuts import render

# def index(request):
#     context = {
#         'title': 'Board list',
#         'board_list': [
#             {'no':1, 'title': '목록1' },
#             {'no':2, 'title': '목록2' },
#             {'no':3, 'title': '목록3' },
#             {'no':4, 'title': '목록4' },
#             {'no':5, 'title': '목록5' }
#         ]
#     }
#     return render(request, 'board/index.html', context)
# index: 게시글 목록

# detail: 게시글 제목 선택 시 상세 페이지 이동

# write: 게시글 목록에서 "글쓰기" 버튼 클릭 시 쓰기 페이지 이동

# write_board: 쓰기 페이지에서 새로운 글을 등록 시에 submit 처리 

# create_reply: 상세 페이지에서 댓글 등록 시에 submit 처리

# POST 데이터 전송(저장) 후 HttpResponseRedirect 를 사용하여 사용자가 뒤로 가기를 했을때 두번 POST 전송 처리 되지 않게 한다.


from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse
from django.db import connection

from .models import Board

def index(request):
    all_boards = Board.objects.all().order_by("-pub_date") # 모든 데이터 조회, 내림차순(-표시) 조회
    return render(request, 'board/index.html', {'title':'Board List', 'board_list':all_boards})

# def detail(request, board_id):
#     board = Board.objects.get(id=board_id)
#     return render(request, 'board/detail.html', {'board': board})

def detail(request, board_id):
    # book1 = get_object_or_404(Book, code=code)
    # book2 = Book.objects.get(code=code)

    try:
        cursor = connection.cursor()

        strSql = "SELECT b.hp, b.age, CASE WHEN b.sex = '01'THEN '남성'WHEN b.sex = '02'THEN '여성' ELSE '성별을 알 수 없음' END as sex, b.pub_date, a.name FROM board_board b LEFT JOIN (SELECT code, name from author) a on a.code = b.author WHERE id = (%s)"
        result = cursor.execute(strSql, (board_id,))
        datas = cursor.fetchall()

        connection.commit()
        connection.close()

        board = {'hp': datas[0][0],
                'age': datas[0][1],
                'sex': datas[0][2],
                'pub_date': datas[0][3],
                'name': datas[0][4]}

    except:
        connection.rollback()
        print("Failed selecting in BookListView")


    return render(request, 'board/detail.html', {'board': board})

def write(request):
    return render(request, 'board/write.html')

def write_board(request):
    b = Board(hp=request.POST['hp'], sex=request.POST['sex'], age=request.POST['age'], author=request.POST['author'], pub_date=timezone.now())
    b.save()
    return HttpResponseRedirect(reverse('board:index'))

# def create_reply(request, board_id):
#     b = Board.objects.get(id = board_id)
#     b.reply_set.create(comment=request.POST['comment'], rep_date=timezone.now())
#     return HttpResponseRedirect(reverse('board:detail', args=(board_id,)))    

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("hello world!")

board/templates/board/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style type="text/css">
        .content {
            max-width:500px;
            margin: auto;
            padding:10px;
        }

		.reply_content {
			text-align:right	
		}

		.reply_content .reply{
			border-radius: 0.5em;
			display: block;
			margin: 4px;
			padding: 3px 10px;
		}

		.board_for_read {
			width: 100%;
			background-color:#f1f1f1;
		}

		#title {
			height: 32px;
			width: 100%;
			border-radius: 0.5em;
			border: none;
			font-family: inherit;
			font-size: inherit;
			background: none;
		}

        textarea {
			width: 100%;
            font-family: inherit;
            font-size: 100%;
			resize: none;
			border-radius: 0.5em;
			padding-block: 10px;
			border: 0px;
			background: none;
        }

		.td_title {
			background-color: #d8d8d8
		}
    </style>
<body>
    <div class="content">

		<table class="board_for_read">
			<tbody>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">HP</td>
					<td style="padding:10px;">
						<input type="text" name="title" id="title" value="{{ board.hp }}" readonly/>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">연령대</td>
					<td style="padding:10px;">
						<span>{{ board.age }}대</span>
					</td>
				</tr>
                <tr>
					<td class="td_title" style="text-align:center; width:20%;">좋아하는작가</td>
					<td style="padding:10px;">
						<span>{{ board.name }}</span>
					</td>
				</tr>
                <tr>
					<td class="td_title" style="text-align:center; width:20%;">성별</td>
					<td style="padding:10px;">
						<span>{{ board.sex }}</span>
					</td>
				</tr>
			</tbody>
		</table>
		<div style="text-align:left;">
			<a href="{% url 'board:index' %}">> Home</a>
		</div>

		
    </div>
</body>
</html>

board/templates/board/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style type="text/css">
        thead {
            background-color:#cecece;
        }

        .content {
            max-width:500px;
            margin: auto;
            padding:10px;
        }

        .header {
            text-align: center;
        }

        .board {
            width: 100%
        }

        .even_bgcolor {
            background-color:#e8efff;
        }
    </style>
<body>
    <div class="content">
        <div class="header">
            <h2>{{ hp }}</h2>
        </div>
        <div style="text-align:right">
            <a href="{% url 'board:write' %}">글쓰기</a>
        </div>

        <table class="board">
            <thead>
                <tr class="header">
                    <th style="width:10%;">순번</th>
                    <th style="width:60%">휴대폰 번호</th>
                    <th style="width:30%">작성일자</th>
                </tr>
            </thead>
            <tbody>
            {% if board_list %}
                {% for data in board_list %}
                <tr class="{% if forloop.counter|divisibleby:2 %}even_bgcolor{% endif %}">
                    <td style="text-align:center;">{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'board:detail' data.id %}">
                            {{ data.hp }}
                        </a>
                    </td>
                    <td>{{ data.pub_date|date:'Y-m-d' }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>작성된 게시글이 없습니다.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</body>
</html>

board/templates/board/write.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style type="text/css">

        .survey-title {
            text-align: center;
            font-weight: bolder;
            margin-bottom: 20px;

        }
        .content {
            max-width: 1000px;
            margin: auto;
            padding:20px;
            align-items: center;
        }

		.board_for_read {
			width: 100%;
			background-color:#f1f1f1;
		}
        textarea {
			width: 100%;
            font-family: inherit;
            font-size: 100%;
			resize: none;
			border-radius: 0.5em;
			padding-block: 10px;
			border: 0px;
        }

		.td_title {
			background-color: #d8d8d8
		}

        .submit-btn-wrap {
            max-width: 1000px;
        }
    </style>
<body>
    <div class="content">
		<form action="{% url 'board:write_board' %}" method="post">
		{% csrf_token %}
        <div class="survey-title">설문조사</div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">HP</span>
            </div>
            <input type="number" name="hp" maxlength="11" placeholder=" -를 빼고 입력해주세요 ex) 01054859059" id="hp" value="{{ board.hp }}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default"  required >
        </div>   
        
        <label for="inputState">연령대</label>
        <select name="age" id="age" value="{{ board.age }}" id="inputState" class="form-control" required>
          <option value="" selected>연령대를 선택해 주세요</option>
          <option value="20">10대</option>
          <option value="20">20대</option>
          <option value="20">30대</option>
          <option value="20">40대</option>
          <option value="20">50대</option>
          <option value="20">60대</option>
          <option value="20">70대</option>
          <option value="20">80대</option>
          <option value="20">90대</option>
        </select>

        <label class="mt-3" for="inputState">좋아하는 작가</label>
        <select name="author" id="author" value="{{ board.author }}" id="inputState" class="form-control" required>
            <option value="" selected>좋아하는 작가를 선택해 주세요</option>
            <option value="01">이중섭</option>
            <option value="02">박수근</option>
            <option value="03">에곤쉴레</option>
            <option value="04">김환기</option>
            <option value="05">고흐</option>
            <option value="06">고갱</option>
            <option value="07">달리</option>
            <option value="08">모네</option>
            <option value="09">뱅크시</option>
          </select> 

         
        <legend class="col-form-label col-sm-12 ">성별</legend>
        <div class="col-sm-12">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="sex" id="sex" value="01" checked>
                <label class="form-check-label" for="sex">
                    남성
                </label>
                </div>
                <div class="form-check">
                <input class="form-check-input" type="radio" name="sex" id="sex" value="02">
                <label class="form-check-label" for="sex">
                    여성
                </label>
                </div>
            </div>

            <div class="submit-btn-wrap mt-3">
                <button type="submit" class="btn btn-primary submit-btn" style=" width: 100%; align-items: center; margin: 0px auto">제출하기</button>
            </div>
        </div>

      
       

        <!-- <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Default</span>
            </div>
            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Default</span>
            </div>
            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Default</span>
            </div>
            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
        </div> -->
          
		<!-- <table class="board_for_read">
			<tbody>
                <tr>
					<td class="td_title" style="text-align:center; width:20%;">휴대폰번호</td>
					<td style="padding:10px;">
						<input type="text" placeholder=" -를 빼고 입력해주세요 ex) 01054859059" name="hp" id="hp" value="{{ board.hp }}"/>
					</td>
				</tr>
                <tr>
					<td class="td_title" style="text-align:center; width:20%;">성별</td>
					<td style="padding:10px;">
						<input type="text" name="sex" id="sex" value="{{ board.sex }}"/>
					</td>
				</tr>
                <tr>
					<td class="td_title" style="text-align:center; width:20%;">나이</td>
					<td style="padding:10px;">
						<input type="text" name="age" id="age" value="{{ board.age }}"/>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">좋아하는작가</td>
					<td style="padding:10px;">
						<input type="text" name="author" id="author" value="{{ board.author }}"/>
					</td>
				</tr>
			</tbody>
		</table> -->

        <!-- <div style="text-align:right;padding: 5px;">
			<input type="submit" value="저장">
		</div> -->
        
        </form>

		<div style="text-align:left;">
			<a href="{% url 'board:index' %}">> Home</a>
		</div>

    </div>
</body>
</html>